### PR TITLE
Improve Gradle and Makefile test cases

### PR DESCRIPTION
**Pull request by dariusf**

### CODE REVIEW

**Comment by codelion** [comment]
@dariusf I wasn't able to build the gradle project on latest Java. Is there a particular version it works on?

```
Asankhayas-MacBook-Pro:multi-modules asankhaya$ srcclr scan --debug
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.util.TrustManagerFromEnv	DEBUG	Skipping additional SSL Trust Manager configuration because both $SRCCLR_SSL_CERT_DIR and $SRCCLR_SSL_CERT_FILE are blank
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.EntryPointImpl	DEBUG	Executing scan with com.sourceclear.agent.commands.ScanCommand
com.sourceclear.agent.EntryPointImpl	DEBUG	SourceClear Agent/3.3.9 (Azul Systems, Inc./11.0.2+9-LTS; arch="x86_64" name="Mac OS X" version="10.14.5" language="en" timezone="America/New_York")
com.sourceclear.agent.EntryPointImpl	DEBUG	Verb Options := verbOpts = {
}
left-overs = []
com.sourceclear.agent.services.LicenseServiceImpl	INFO 	Checking Agent authentication against the SourceClear API...
com.sourceclear.util.io.GitUtils	DEBUG	git status --porcelain stdout: 
com.sourceclear.util.io.GitUtils	DEBUG	git status --porcelain stderr: 
com.sourceclear.agent.commands.ScanCommand	DEBUG	Scanning local directory with upload. Repo is clean. Proceeding...
com.sourceclear.agent.commands.ScanCommand	DEBUG	Scan collectors: 
com.sourceclear.agent.commands.ScanCommand	DEBUG	Skip collectors: 
com.sourceclear.agent.commands.ScanCommand	DEBUG	Skip vulnerable methods: false
com.sourceclear.agent.commands.ScanCommand	DEBUG	Setup completed in 0s
com.sourceclear.engine.component.ComponentEngineBuilder	DEBUG	collectorsToRun: []
com.sourceclear.engine.component.ComponentEngineBuilder	DEBUG	collectorsToSkip: []
SourceClear scanning engine ready
com.sourceclear.agent.services.ConfigServiceImpl	DEBUG	Using config file at "/Users/asankhaya/.srcclr/agent.yml"
com.sourceclear.agent.services.ScanServiceImpl	DEBUG	Beginning dependency analysis
Running the Gradle scanner
com.sourceclear.engine.component.NativeLocalEngine	DEBUG	Collector "Gradle" started
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	FAILURE: Build failed with an exception.
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	* What went wrong:
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	Could not determine java version from '12.0.1'.
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	* Try:
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	Executing '/Users/asankhaya/git/efda/java/gradle/multi-modules/gradlew --version' to get gradle version.
com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	non-zero rc when getting gradle version: 1. stderr: 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	version found from executing '/Users/asankhaya/git/efda/java/gradle/multi-modules/gradlew': 'Optional.empty'
com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	default scope set to: compile
com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	GRADLE_TASKS is neither a string or a list: null
com.sourceclear.engine.component.collectors.GradleNativeCollector	DEBUG	Running default tasks: [projects, classes]
com.sourceclear.engine.component.collectors.GradleNativeCollector	INFO 	Running Gradle Graph Building with: /Users/asankhaya/git/efda/java/gradle/multi-modules/gradlew -Psrcclr.graph.location=/var/folders/8g/6318h_294_50lq3drcthxrr40000gp/T/graph-3897482977608724231.json -Psrcclr.scope=compile --init-script /var/folders/8g/6318h_294_50lq3drcthxrr40000gp/T/init-1831441623383698571.gradle projects classes
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	FAILURE: Build failed with an exception.
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	* What went wrong:
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	Could not determine java version from '12.0.1'.
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	* Try:
com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector	INFO 	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Encountered errors while collecting component information.
Processing results...
com.sourceclear.engine.scan.PlatformScan	DEBUG	Evidence set is empty after collection.
com.sourceclear.api.client.SourceClearClient	DEBUG	Skipping post-fact status code check because of retry-mode (but, code=200 status=null)
com.sourceclear.engine.scan.PlatformScan	DEBUG	Matched in 0 seconds.
Processing results complete
com.sourceclear.agent.EntryPointImpl	DEBUG	Exiting with 1
com.sourceclear.agent.FatalException: This project does not seem to build.
Because of this, SourceClear cannot scan it. Please ensure that the project compiles prior to scanning.
	at com.sourceclear.agent.commands.ScanCommand.handleScanErrors(ScanCommand.java:1004)
	at com.sourceclear.agent.commands.ScanCommand.executeRepoScan(ScanCommand.java:782)
	at com.sourceclear.agent.commands.ScanCommand.execute(ScanCommand.java:476)
	at com.sourceclear.agent.EntryPointImpl.runVerb(EntryPointImpl.java:372)
	at com.sourceclear.agent.EntryPointImpl.dispatchVerbOptions(EntryPointImpl.java:321)
	at com.sourceclear.agent.EntryPointImpl.apply(EntryPointImpl.java:157)
	at com.sourceclear.agent.Main.main(Main.java:96)
Caused by: com.sourceclear.engine.component.CollectionException: This project does not seem to build.
Because of this, SourceClear cannot scan it. Please ensure that the project compiles prior to scanning.
	at com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector.handleNonZeroProcessExit(JsonComponentGraphNativeCollector.java:176)
	at com.sourceclear.engine.component.collectors.JsonComponentGraphNativeCollector.collect(JsonComponentGraphNativeCollector.java:128)
	at com.sourceclear.engine.component.collectors.GradleNativeCollector.collect(GradleNativeCollector.java:49)
	at com.sourceclear.engine.component.NativeLocalEngine.collect(NativeLocalEngine.java:96)
	at com.sourceclear.agent.services.ScanServiceImpl.performScanEx(ScanServiceImpl.java:573)
	at com.sourceclear.agent.services.ScanServiceImpl.performScan(ScanServiceImpl.java:447)
	at com.sourceclear.agent.commands.ScanCommand.lambda$executeRepoScan$5(ScanCommand.java:790)
	at com.sourceclear.agent.commands.ScanCommand.handleScanErrors(ScanCommand.java:984)
	... 6 more
```

**Comment by dariusf** [comment]
Tried it on 1.8.0_181. Unfortunately we don't support Gradle 5+ yet, which would be required to build with Java 12.

**Comment by dariusf** [comment]
Also updated the spreadsheet with a bunch of package managers.

**Review by codelion — APPROVED** [review]

**Comment by codelion** [comment]
fixes #14 .

**Pull request merged**
